<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AYAN" ignored="1" name="Default test(failed)" tests="2" failures="1" timestamp="2020-06-11T00:35:39 IST" time="0.107" errors="0">
  <testcase name="test2" time="0.015" classname="testng.TestNGRetryFailedDemo"/>
  <testcase name="test3" time="0.018" classname="testng.TestNGRetryFailedDemo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:22)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.0" classname="testng.TestNGRetryFailedDemo">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
